# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{solvemedia}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eddie Siegel"]
  s.date = %q{2010-01-21}
  s.description = %q{Simplifies the use of Solve Media puzzles within rails applications}
  s.email = %q{plugin@solvemedia.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "solvemedia.gemspec",
     "generators/solvemedia_config/USAGE",
     "generators/solvemedia_config/solvemedia_config_generator.rb",
     "generators/solvemedia_config/templates/solvemedia_config.yml",
     "init.rb",
     "install.rb",
     "lib/solvemedia.rb",
     "lib/controller_methods.rb",
     "lib/view_methods.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://portal.solvemedia.com/portal/help/pub/ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simplifies the use of Solve Media puzzles within rails applications}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

